config/routes.rb
Rails.application.routes.draw do

  get 'signup', :to => 'users#new'
  get 'login', :to => 'sessions#login'
  get 'logout', :to => 'sessions#logout'
  get 'home', :to => 'sessions#home'
  get 'profile', :to => 'sessions#profile'
  get 'setting', :to => 'sessions#setting'

  match 'catalog/latest', :to => 'catalog#latest', via: [:get, :post]

  get 'catalog/index'

  get 'catalog/show'

  get 'catalog/search'

  get 'catalog/latest'

  namespace :admin do
    resources :author
    resources :publishers
    resources :books
    resources :products
  end

  get 'about/index'

  scope :module => 'admin' do
    resources :books
    resources :products
  end

  root :to => 'catalog#index'
  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]

end

app/models/product.rb
class Product < ActiveRecord::Base


  has_attached_file :cover_image,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover_image,
                                    :content_type => /\Aimage\/.*\Z/

  has_many :cart_items
  has_many :carts, :through => :cart_items

  validates_length_of :title, :in => 1..255
  validates :seller_info, :presence => true
  validates :description, :presence => true
  validates_numericality_of :amount, :only_integer => true
  validates :types, :presence => true
  validates :category, :presence  => true
  validates_numericality_of :price, :only_integer => true
# roughly speaking sets list of model protected attributes to []
# making all attributes accessible while mass-assignment
  attr_protected

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_filter :authenticate_user, :only => [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @page_title = t(:listing_products)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t(:product_was_successfully_created) }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: t(:product_was_successfully_updated) }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice:  t(:product_was_successfully_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :seller_info, :description, :amount, :types, :category, :price, :created_at, :updated_at, :cover_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:title) %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label t(:seller_info) %><br>
    <%= f.text_field :seller_info %>
  </div>
  <div class="field">
    <%= f.label t(:description) %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label t(:amount) %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label t(:type) %><br>
    <%= f.text_field :types %>
  </div>
  <div class="field">
    <%= f.label t(:category) %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label t(:price) %><br>
    <%= f.text_field :price %>
  </div>
    <div class="field">
      <label for="book_cover_image"><%= t(:pr_image) %></label><br>
      <%= file_field 'product', 'cover_image' %>
    </div>

  <div class="actions">
    <%= f.submit :class => 'buttons' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1><%= t(:edit_it)%></h1>

<%= form_tag({:action => 'update', :id => @product},
             {:multipart => true, :method => :put}) do %>
    <%= render :partial => 'form' %>
<% end %>

<%= link_to t(:show_it), :action => 'show', :id => @product %> |
<%= link_to t(:back_it), :action => 'index' %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th><%= t(:title)%></th>
      <th><%= t(:seller_info)%></th>
      <th><%= t(:amount)%></th>
      <th><%= t(:type)%></th>
      <th><%= t(:category)%></th>
      <th><%= t(:price)%></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.seller_info %></td>
        <td><%= product.amount %></td>
        <td><%= product.types %></td>
        <td><%= product.category %></td>
        <td><%= product.price %></td>
        <td><%= link_to t(:show_it), :action => 'show', :id => product %></td>
        <td><%= link_to t(:edit_it),:action => 'edit', :id => product %></td>
        <td><%= link_to t(:destroy_it), product, :method => :delete,  data: { confirm: t(:are_you_shure_delete) }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to t(:new_product), :action => 'new' %>

app/views/admin/products/new.html.erb
<h1><%= t(:new_product) %></h1>

<%= form_tag( {:action => 'create'}, :multipart => true ) do %>
    <%= render :partial => 'form' %>
<% end %>

<%= link_to t(:back_it), admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(:title) %>:</strong>
  <%= @product.title %>
</p>

<p>
  <strong><%= t(:seller_info) %>:</strong>
  <%= @product.seller_info %>
</p>

<p>
  <strong><%= t(:description) %></strong>
  <%= @product.description %>
</p>

<p>
  <strong><%= t(:amount) %>:</strong>
  <%= @product.amount %>
</p>

<p>
  <strong><%= t(:type) %>:</strong>
  <%= @product.types %>
</p>

<p>
  <strong><%= t(:category) %>:</strong>
  <%= @product.category %>
</p>

<p>
  <strong><%= t(:price) %>:</strong>
  <%= @product.price %>
</p>

<p><strong><%= t(:pr_image)%>:</strong></p>
<% if @product.cover_image.nil? %>
    <dd>N/A</dd>
<% else %>
    <dd><%= image_tag @product.cover_image.url %></dd>
<% end %>

<%= link_to t(:edit_it), edit_admin_product_path(@product) %> |
<%= link_to t(:back_it), admin_products_path %>